In [1]:
import numpy as np
import pandas as p
import pygame as pg
from scipy.spatial import distance_matrix

from game_functions import *
from class_herbivore_nn import *
from class_world import *

pygame 2.1.2 (SDL 2.0.18, Python 3.10.1)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
a = np.array([1,2,3,4,5])
np.argmax(a)

4

In [ ]:
a = AnimalBrain(n_ray_sections=1,n_types_of_info_in_each_section=1,hidden_dim_1=2,hidden_dim_2=1)
a.get_dim_sizes()


(2, 1)

In [5]:
a = AnimalBrain(n_ray_sections=1,n_types_of_info_in_each_section=1,hidden_dim_1=1,hidden_dim_2=1)
print(a.get_dim_sizes())
for i in a.parameters():
    print(i)
print("------------")
b = resize_layer_in_animal_brain(a, layer="fc2", new_size = 2, init_std =0.5)
for i in b.parameters():
    print(i)
print(b.get_dim_sizes())


(1, 1)
Parameter containing:
tensor([[ 0.0253, -0.4105, -0.3115, -0.4163]], requires_grad=True)
Parameter containing:
tensor([[0.1312]], requires_grad=True)
Parameter containing:
tensor([[-0.6843],
        [ 0.2380]], requires_grad=True)
------------
Parameter containing:
tensor([[ 0.0253, -0.4105, -0.3115, -0.4163]], requires_grad=True)
Parameter containing:
tensor([[ 0.1312],
        [-0.5761]], requires_grad=True)
Parameter containing:
tensor([[-0.6843, -0.0865],
        [ 0.2380, -0.5680]], requires_grad=True)
(1, 2)


In [14]:
np.random.randint(low=1,high=4,size=1)[0]

2

In [25]:
a = np.array([True, True, False])
b = np.array([1,2,3])
c = np.empty((1,2))
np.append(c,[a,b])

array([0.e+000, 5.e-324, 1.e+000, 1.e+000, 0.e+000, 1.e+000, 2.e+000,
       3.e+000])

In [12]:
np.random.choice([-1,1])
np.clip(([3,10][1]+np.random.choice([-1,1])),a_min=1,a_max=20)

9

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class HerbBrain(nn.Module):
    def __init__(self, n_rays=6, n_channels=2, hidden_dim=12):
        """
        n_rays: Number of raycasts (e.g., 5)
        n_channels: Channels per ray (e.g., 3 for food, wall, predator)
        hidden_dim: Size of hidden layers (controls NN capacity)
        """
        super().__init__()

        input_dim = n_rays * n_channels    
        output_dim = 2   #acceleration and angular velocity
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.out = nn.Linear(hidden_dim, output_dim)

    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.tanh(self.out(x))
        return x

In [ ]:
torch.manual_seed(41)
model = HerbBrain()
mutation_rate = 0.5
mutation_strength = 0.1
for param in model.parameters():
    print(param.shape)
    if len(param.shape) == 2:  # Weights
        mask = torch.rand_like(param) < mutation_rate
        noise = torch.randn_like(param) * mutation_strength
        param.data += mask * noise
    elif len(param.shape) == 1:  # Biases
        mask = torch.rand_like(param) < mutation_rate
        noise = torch.randn_like(param) * mutation_strength
        param.data += mask * noise

torch.Size([12, 12])
Parameter containing:
tensor([[-0.1522, -0.1578,  0.1735, -0.1910, -0.1357,  0.1570, -0.2147,  0.1416,
          0.1758,  0.0784,  0.0517,  0.1116],
        [ 0.2184,  0.0235, -0.2078,  0.2664,  0.2117, -0.0067, -0.1688, -0.1118,
         -0.2549,  0.1913, -0.0251,  0.1989],
        [ 0.1087, -0.0573, -0.1846,  0.1005, -0.1852, -0.0642,  0.1716, -0.1572,
         -0.0141, -0.0392,  0.0331,  0.2779],
        [ 0.1688, -0.1084,  0.2555, -0.0939,  0.1189,  0.1195, -0.0087, -0.2686,
          0.2714, -0.0667,  0.1966, -0.1731],
        [-0.0295,  0.2475, -0.2505,  0.0111, -0.0038, -0.2467, -0.0559, -0.2646,
          0.0624,  0.0486,  0.1652,  0.0072],
        [-0.1162, -0.1041, -0.1078,  0.2246,  0.0925, -0.2874,  0.0516, -0.0385,
          0.2106, -0.0844,  0.2520,  0.0892],
        [-0.2601,  0.0607, -0.0659,  0.1445, -0.2478, -0.0211,  0.1908,  0.1023,
          0.1358,  0.2444,  0.1179,  0.0938],
        [ 0.0595,  0.0190,  0.2513, -0.0666,  0.0380,  0.0040, -0.07

In [56]:
a = np.array([1,2,3,4])
a=a[0:3]
a

array([1, 2, 3])

In [49]:
a = np.array([1,2,3,4,5])
a[[]] = 99
a
np.random.randint(0,1,2)

array([0, 0])

In [3]:
np.random.rand((5))

array([0.79039178, 0.65604093, 0.37642192, 0.81664141, 0.49718563])

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([0,0,0,0,0,0,0,0,0,0])
b = b[:,np.newaxis]
c = a+b
d = (c**2)*2

e = np.zeros((10,5,2))
e[0]



array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
bonk = World()
print(bonk.current_plant)
bonk.spawn_food(25)
print(bonk.current_plant)
bonk.remove_food(0)
print(bonk.current_plant)

0
50
25
24


In [26]:
test = pg.time.Clock()
print(test.tick(30))
print(test.tick(30))

33
33


In [ ]:
angles = np.array([0.1,0.2,1.5,3.14])
speeds = np.array([0,5,10,15])
dpos = np.zeros((angles.size,2))

np.sin(angles, out=dpos[:,0])
np.cos(angles, out=dpos[:,1])

dpos = dpos*speeds[:, np.newaxis]

speeds[[0,1,3],np.newaxis]

array([[ 0],
       [ 5],
       [15]])

In [125]:
a = np.array([[1,1],[2,2],[3,3],[4,4]])
b = np.array([[1,1],[3,3],[2,2]])
result = np.column_stack(np.where(distance_matrix(a,b)<0.1))
result

array([[0, 0],
       [1, 2],
       [2, 1]], dtype=int64)

In [17]:
a = np.array([1,2,3,4])
alive = np.array([True,True,False,True])
b = np.where(alive)[0]
c = b[[1,2]]
a[c] = 99
a

array([ 1, 99,  3, 99])

In [76]:
start_point = np.array([1,1]) # represents position of single herbivore
end_points = np.array([[1,10],[5,5]]) # representes end points of two rays
vectors = end_points - start_point 
points = np.array([[10,10],[3,3],[-2,6]]) #represents three units of food

point_vec = points[:, np.newaxis, :] - start_point[np.newaxis, np.newaxis,:]
ray_len_sq = np.sum(vectors**2, axis=1)  # shape (R,)
t = np.sum(point_vec * vectors[np.newaxis, :, :], axis=2) / ray_len_sq  # shape (P, R)
closest = start_point[np.newaxis, :] + (t[..., np.newaxis] * vectors[np.newaxis, :, :])
closest #closest distance of each plant to each vector

array([[[ 1., 10.],
        [10., 10.]],

       [[ 1.,  3.],
        [ 3.,  3.]],

       [[ 1.,  6.],
        [ 2.,  2.]]])

In [5]:
h = np.array([[1,1],[5,5]])
r = np.array([ [[10,1],
                [6,10],
                [-105,1]],
               [[1,1],
                [7,9],
                [7,100]] ])
p = np.array([[8,9],[11,1],[-4,1]])
size = 1
a,b = raycast_detect_plant_and_wall(p,h,r,(200,200))
a



array([[0.        , 0.        , 5.        ],
       [0.        , 0.        , 4.06225777]])